# Generated by Django 3.2.8 on 2022-01-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='weapon_dmg',
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_dmg_1',
            field=models.CharField(choices=[('1', '4'), ('2', '6'), ('3', '8'), ('4', '10'), ('5', '12')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(choices=[('1', 'Heavy'), ('2', 'Finese'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=20),
        ),
    ]
