# Generated by Django 3.2.8 on 2022-01-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220119_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='weapon_dmg_2',
            field=models.CharField(choices=[('1', '4'), ('2', '6'), ('3', '8'), ('4', '10'), ('5', '12')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_dmg_1',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=20),
        ),
    ]
