# Generated by Django 3.2.8 on 2022-01-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20220120_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='modifier',
            field=models.IntegerField(blank=True, db_column='Modifier', null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='rarity',
            field=models.CharField(blank=True, db_column='Rarity', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='armor',
            name='weight',
            field=models.IntegerField(blank=True, db_column='Weight', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='modifiers',
            field=models.IntegerField(blank=True, db_column='Modifiers', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(blank=True, db_column='Rarity', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.IntegerField(blank=True, db_column='Weight', null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='modifier',
            field=models.IntegerField(blank=True, db_column='Modifier', null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='rarity',
            field=models.CharField(blank=True, db_column='Rarity', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weight',
            field=models.IntegerField(blank=True, db_column='Weight', null=True),
        ),
    ]
