# Generated by Django 3.2.8 on 2022-01-21 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_char_race_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armor',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='char_class',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='char_race',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='desc',
            new_name='description',
        ),
    ]
